/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.timsu.astrid;

public final class R {
    public static final class anim {
        public static final int slide_left_in=0x7f040000;
        public static final int slide_left_out=0x7f040001;
        public static final int slide_right_in=0x7f040002;
        public static final int slide_right_out=0x7f040003;
    }
    public static final class array {
        /**  Astrid says...  (user should answer yes or no)
         */
        public static final int reminder_responses=0x7f060001;
        /**  Make these < 20 chars so the task name is displayed 
         */
        public static final int reminders=0x7f060000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int importance_1=0x7f07000f;
        public static final int importance_2=0x7f070010;
        public static final int importance_3=0x7f070011;
        public static final int importance_4=0x7f070012;
        public static final int taskList_completedDate=0x7f07000a;
        public static final int taskList_details=0x7f07000b;
        public static final int taskList_dueDate=0x7f070008;
        public static final int taskList_dueDateOverdue=0x7f070007;
        public static final int taskList_remainingTime=0x7f070009;
        public static final int task_list_done=0x7f070002;
        public static final int task_list_importance_1=0x7f070003;
        public static final int task_list_importance_2=0x7f070004;
        public static final int task_list_importance_3=0x7f070005;
        public static final int task_list_importance_4=0x7f070006;
        public static final int task_list_normal=0x7f070001;
        public static final int task_list_overdue=0x7f070000;
        public static final int view_header_done=0x7f07000c;
        public static final int view_table_overdue=0x7f07000e;
        public static final int view_table_values=0x7f07000d;
    }
    public static final class drawable {
        public static final int btn_check0=0x7f020000;
        public static final int btn_check25=0x7f020001;
        public static final int btn_check50=0x7f020002;
        public static final int btn_check75=0x7f020003;
        public static final int btn_check_0=0x7f020004;
        public static final int btn_check_25=0x7f020005;
        public static final int btn_check_50=0x7f020006;
        public static final int btn_check_75=0x7f020007;
        public static final int btn_check_off=0x7f020008;
        public static final int btn_check_off_pressed=0x7f020009;
        public static final int btn_check_on=0x7f02000a;
        public static final int btn_check_on_pressed=0x7f02000b;
        public static final int bubble_blue=0x7f02000c;
        public static final int bubble_gray=0x7f02000d;
        public static final int bubble_red=0x7f02000e;
        public static final int bubble_yellow=0x7f02000f;
        public static final int ic_dialog_alert_c=0x7f020010;
        public static final int ic_dialog_info_c=0x7f020011;
        public static final int ic_dialog_time=0x7f020012;
        public static final int ic_dialog_time_c=0x7f020013;
        public static final int icon=0x7f020014;
        public static final int icon_timer=0x7f020015;
        public static final int notification_clock=0x7f020016;
        public static final int notification_icon=0x7f020017;
        public static final int notification_tag_pink=0x7f020018;
        public static final int timepicker_down_btn=0x7f020019;
        public static final int timepicker_down_disabled=0x7f02001a;
        public static final int timepicker_down_disabled_focused=0x7f02001b;
        public static final int timepicker_down_normal=0x7f02001c;
        public static final int timepicker_down_pressed=0x7f02001d;
        public static final int timepicker_down_selected=0x7f02001e;
        public static final int timepicker_input=0x7f02001f;
        public static final int timepicker_input_disabled=0x7f020020;
        public static final int timepicker_input_normal=0x7f020021;
        public static final int timepicker_input_pressed=0x7f020022;
        public static final int timepicker_input_selected=0x7f020023;
        public static final int timepicker_up_btn=0x7f020024;
        public static final int timepicker_up_disabled=0x7f020025;
        public static final int timepicker_up_disabled_focused=0x7f020026;
        public static final int timepicker_up_normal=0x7f020027;
        public static final int timepicker_up_pressed=0x7f020028;
        public static final int timepicker_up_selected=0x7f020029;
    }
    public static final class id {
        public static final int addAlert=0x7f0b0036;
        public static final int addtask=0x7f0b003e;
        public static final int alert_container=0x7f0b0035;
        public static final int alerts_label=0x7f0b0034;
        public static final int btn_tasklist=0x7f0b004f;
        public static final int btn_viewtask=0x7f0b004e;
        public static final int button=0x7f0b0003;
        public static final int button1=0x7f0b0002;
        public static final int button_layout=0x7f0b0052;
        public static final int cb1=0x7f0b0041;
        public static final int cell_creationDate=0x7f0b005a;
        public static final int cell_definiteDueDate=0x7f0b0058;
        public static final int cell_elapsed=0x7f0b0055;
        public static final int cell_estimated=0x7f0b0056;
        public static final int cell_notes=0x7f0b0057;
        public static final int cell_preferredDueDate=0x7f0b0059;
        public static final int container=0x7f0b0005;
        public static final int date=0x7f0b0000;
        public static final int decrement=0x7f0b0008;
        public static final int definiteDueDate_date=0x7f0b0022;
        public static final int definiteDueDate_label=0x7f0b0020;
        public static final int definiteDueDate_notnull=0x7f0b0021;
        public static final int definiteDueDate_time=0x7f0b0023;
        public static final int delete=0x7f0b001e;
        public static final int discard=0x7f0b001d;
        public static final int edit=0x7f0b005b;
        public static final int elapsedDuration=0x7f0b0030;
        public static final int elapsedDuration_label=0x7f0b002f;
        public static final int estimatedDuration=0x7f0b0019;
        public static final int estimatedDuration_label=0x7f0b0018;
        public static final int event=0x7f0b0011;
        public static final int flag_after=0x7f0b003a;
        public static final int flag_before=0x7f0b0038;
        public static final int flag_during=0x7f0b0039;
        public static final int flag_nonstop=0x7f0b003b;
        public static final int flags_label=0x7f0b0037;
        public static final int footer=0x7f0b000a;
        public static final int forget=0x7f0b000b;
        public static final int frame=0x7f0b000f;
        public static final int greeting=0x7f0b004c;
        public static final int hiddenUntil_date=0x7f0b002a;
        public static final int hiddenUntil_label=0x7f0b0028;
        public static final int hiddenUntil_notnull=0x7f0b0029;
        public static final int hiddenUntil_time=0x7f0b002b;
        public static final int icon_layout=0x7f0b0040;
        public static final int imageLeft=0x7f0b0042;
        public static final int importance=0x7f0b004b;
        public static final int importance_container=0x7f0b0015;
        public static final int importance_label=0x7f0b0014;
        public static final int increment=0x7f0b0006;
        public static final int name=0x7f0b0013;
        public static final int name_label=0x7f0b0012;
        public static final int notes=0x7f0b001b;
        public static final int notes_label=0x7f0b001a;
        public static final int notification=0x7f0b0033;
        public static final int notification_label=0x7f0b0032;
        public static final int numberPicker=0x7f0b0009;
        public static final int preferredDueDate_date=0x7f0b0026;
        public static final int preferredDueDate_label=0x7f0b0024;
        public static final int preferredDueDate_notnull=0x7f0b0025;
        public static final int preferredDueDate_time=0x7f0b0027;
        public static final int progress=0x7f0b0054;
        public static final int repeat_interval=0x7f0b002e;
        public static final int repeat_label=0x7f0b002c;
        public static final int repeat_value=0x7f0b002d;
        public static final int row_layout=0x7f0b003f;
        public static final int save=0x7f0b001c;
        public static final int scroll_view=0x7f0b0050;
        public static final int sync=0x7f0b000c;
        public static final int tab_basic=0x7f0b0010;
        public static final int tab_dates=0x7f0b001f;
        public static final int tab_notification=0x7f0b0031;
        public static final int taglist=0x7f0b000e;
        public static final int taglist_layout=0x7f0b000d;
        public static final int tags_container=0x7f0b0017;
        public static final int tags_label=0x7f0b0016;
        public static final int task_name=0x7f0b0044;
        public static final int tasklist=0x7f0b003d;
        public static final int tasklist_layout=0x7f0b003c;
        public static final int taskname=0x7f0b004d;
        public static final int text1=0x7f0b0004;
        public static final int text_deadlines=0x7f0b0045;
        public static final int text_layout=0x7f0b0043;
        public static final int text_notes=0x7f0b004a;
        public static final int text_reminders=0x7f0b0048;
        public static final int text_repeats=0x7f0b0047;
        public static final int text_tags=0x7f0b0049;
        public static final int text_times=0x7f0b0046;
        public static final int time=0x7f0b0001;
        public static final int timepicker_input=0x7f0b0007;
        public static final int timerButton=0x7f0b0053;
        public static final int view_layout=0x7f0b0051;
    }
    public static final class layout {
        public static final int edit_alert_item=0x7f030000;
        public static final int edit_importance_item=0x7f030001;
        public static final int edit_tag_item=0x7f030002;
        public static final int importance_spinner_dropdown=0x7f030003;
        public static final int n_number_picker_dialog=0x7f030004;
        public static final int number_picker=0x7f030005;
        public static final int number_picker_dialog=0x7f030006;
        public static final int sync_footer=0x7f030007;
        public static final int tag_list=0x7f030008;
        public static final int task_edit=0x7f030009;
        public static final int task_list=0x7f03000a;
        public static final int task_list_row=0x7f03000b;
        public static final int task_notify=0x7f03000c;
        public static final int task_view=0x7f03000d;
    }
    public static final class plurals {
        public static final int NactiveTasks=0x7f090001;
        public static final int Nalarms=0x7f090002;
        /**  Time Constants 
         */
        public static final int Ndays=0x7f090004;
        public static final int Nhours=0x7f090005;
        public static final int Nminutes=0x7f090006;
        public static final int Nseconds=0x7f090007;
        public static final int Ntags=0x7f090003;
        /**  Plurals 
         */
        public static final int Ntasks=0x7f090000;
    }
    public static final class string {
        public static final int add_alert=0x7f08004c;
        public static final int addtask_label=0x7f08000d;
        public static final int ago_suffix=0x7f080066;
        public static final int alerts_label=0x7f08004b;
        /**  application 
         */
        public static final int app_name=0x7f080000;
        public static final int blank_button_title=0x7f080056;
        public static final int blockingOn_label=0x7f080041;
        public static final int daysVertical=0x7f080008;
        public static final int definiteDueDate_label=0x7f08003c;
        public static final int delete_label=0x7f080055;
        public static final int delete_this_tag_title=0x7f080091;
        public static final int delete_this_task_title=0x7f080090;
        public static final int delete_title=0x7f08008f;
        public static final int discard_label=0x7f080054;
        public static final int displayedFields_PrefScreen_Desc=0x7f0800b4;
        public static final int displayedFields_PrefScreen_Title=0x7f0800b3;
        public static final int edit_label=0x7f08005d;
        public static final int elapsedDuration_label=0x7f08003b;
        public static final int error_opening=0x7f080096;
        public static final int error_saving=0x7f080097;
        public static final int estimatedDuration_label=0x7f08003a;
        public static final int flag_after=0x7f080049;
        public static final int flag_before=0x7f080047;
        public static final int flag_during=0x7f080048;
        public static final int flag_nonstop=0x7f08004a;
        public static final int flags_label=0x7f080046;
        public static final int hiddenUntil_label=0x7f08003e;
        /**  dialog boxes 
         */
        public static final int hour_minutes_dialog=0x7f08004d;
        public static final int hoursVertical=0x7f080009;
        /**  Importance Labels 
         */
        public static final int importance_1=0x7f080001;
        public static final int importance_2=0x7f080002;
        public static final int importance_3=0x7f080003;
        public static final int importance_4=0x7f080004;
        public static final int importance_label=0x7f080038;
        public static final int information_title=0x7f080089;
        public static final int name_hint=0x7f080037;
        /**  labels 
         */
        public static final int name_label=0x7f080036;
        public static final int notes_hint=0x7f080043;
        public static final int notes_label=0x7f080042;
        public static final int notif_definiteDueDate=0x7f080093;
        public static final int notif_preferredDueDate=0x7f080094;
        public static final int notif_timerStarted=0x7f080095;
        public static final int notification_dialog=0x7f08004e;
        public static final int notification_label=0x7f080044;
        public static final int notification_prefix=0x7f080045;
        public static final int notify_no=0x7f08008d;
        public static final int notify_snooze=0x7f08008c;
        public static final int notify_snooze_title=0x7f08008e;
        public static final int notify_yes=0x7f08008b;
        public static final int overdue_suffix=0x7f080065;
        public static final int p_colorize=0x7f0800a9;
        public static final int p_deadlineTime=0x7f0800b0;
        public static final int p_fontSize=0x7f0800ac;
        public static final int p_notif_annoy=0x7f0800a2;
        public static final int p_notif_defaultRemind=0x7f08009f;
        public static final int p_notif_quietEnd=0x7f08009c;
        public static final int p_notif_quietStart=0x7f080099;
        public static final int p_notification_ringtone=0x7f0800a5;
        public static final int p_sync_background=0x7f08007f;
        public static final int p_sync_button=0x7f080079;
        public static final int p_sync_every=0x7f080076;
        public static final int p_sync_quiet=0x7f08007c;
        public static final int p_sync_rtm=0x7f080073;
        public static final int preferredDueDate_label=0x7f08003d;
        public static final int prefs_annoy_desc=0x7f0800a4;
        public static final int prefs_annoy_title=0x7f0800a3;
        public static final int prefs_category_alerts=0x7f080098;
        public static final int prefs_category_appearance=0x7f0800a8;
        public static final int prefs_category_other=0x7f0800af;
        public static final int prefs_colorize_desc=0x7f0800ab;
        public static final int prefs_colorize_title=0x7f0800aa;
        public static final int prefs_deadlineTime_desc=0x7f0800b2;
        public static final int prefs_deadlineTime_title=0x7f0800b1;
        public static final int prefs_deadlineVisible=0x7f0800b9;
        public static final int prefs_deadlineVisible_default=0x7f0800bc;
        public static final int prefs_deadlineVisible_desc=0x7f0800bb;
        public static final int prefs_deadlineVisible_title=0x7f0800ba;
        public static final int prefs_defaultRemind_desc=0x7f0800a1;
        public static final int prefs_defaultRemind_title=0x7f0800a0;
        public static final int prefs_fontSize_desc=0x7f0800ae;
        public static final int prefs_fontSize_title=0x7f0800ad;
        public static final int prefs_importanceVisible=0x7f0800c1;
        public static final int prefs_importanceVisible_default=0x7f0800c4;
        public static final int prefs_importanceVisible_desc=0x7f0800c3;
        public static final int prefs_importanceVisible_title=0x7f0800c2;
        public static final int prefs_notesVisible=0x7f0800d1;
        public static final int prefs_notesVisible_default=0x7f0800d4;
        public static final int prefs_notesVisible_desc=0x7f0800d3;
        public static final int prefs_notesVisible_title=0x7f0800d2;
        public static final int prefs_notification_desc=0x7f0800a7;
        public static final int prefs_notification_title=0x7f0800a6;
        public static final int prefs_quietEnd_desc=0x7f08009e;
        public static final int prefs_quietEnd_title=0x7f08009d;
        public static final int prefs_quietStart_desc=0x7f08009b;
        public static final int prefs_quietStart_title=0x7f08009a;
        public static final int prefs_reminderVisible=0x7f0800cd;
        public static final int prefs_reminderVisible_default=0x7f0800d0;
        public static final int prefs_reminderVisible_desc=0x7f0800cf;
        public static final int prefs_reminderVisible_title=0x7f0800ce;
        public static final int prefs_repeatVisible=0x7f0800c9;
        public static final int prefs_repeatVisible_default=0x7f0800cc;
        public static final int prefs_repeatVisible_desc=0x7f0800cb;
        public static final int prefs_repeatVisible_title=0x7f0800ca;
        public static final int prefs_tagsVisible=0x7f0800c5;
        public static final int prefs_tagsVisible_default=0x7f0800c8;
        public static final int prefs_tagsVisible_desc=0x7f0800c7;
        public static final int prefs_tagsVisible_title=0x7f0800c6;
        public static final int prefs_timeVisible=0x7f0800bd;
        public static final int prefs_timeVisible_default=0x7f0800c0;
        public static final int prefs_timeVisible_desc=0x7f0800bf;
        public static final int prefs_timeVisible_title=0x7f0800be;
        public static final int prefs_titleVisible=0x7f0800b5;
        public static final int prefs_titleVisible_default=0x7f0800b8;
        public static final int prefs_titleVisible_desc=0x7f0800b7;
        public static final int prefs_titleVisible_title=0x7f0800b6;
        public static final int progress_dialog=0x7f080067;
        public static final int progress_suffix=0x7f08005c;
        public static final int question_title=0x7f08008a;
        /**  Repeat Interval Labels 
         */
        public static final int repeat_days=0x7f080005;
        public static final int repeat_help_dialog=0x7f080051;
        public static final int repeat_help_dialog_title=0x7f080050;
        public static final int repeat_help_hide=0x7f080052;
        public static final int repeat_label=0x7f08003f;
        public static final int repeat_months=0x7f080007;
        public static final int repeat_picker_title=0x7f08004f;
        public static final int repeat_value_unset=0x7f080040;
        public static final int repeat_weeks=0x7f080006;
        /**  buttons 
         */
        public static final int save_label=0x7f080053;
        public static final int startTimer_label=0x7f08005a;
        public static final int stopTimer_label=0x7f08005b;
        public static final int stop_timer_title=0x7f080092;
        public static final int sync_auth_request=0x7f080083;
        public static final int sync_background_desc=0x7f080081;
        public static final int sync_background_title=0x7f080080;
        public static final int sync_button_desc=0x7f08007b;
        public static final int sync_button_title=0x7f08007a;
        public static final int sync_error=0x7f080082;
        public static final int sync_every_desc=0x7f080078;
        public static final int sync_every_title=0x7f080077;
        public static final int sync_forget=0x7f080086;
        public static final int sync_forget_confirm=0x7f080087;
        public static final int sync_no_synchronizers=0x7f080088;
        public static final int sync_now=0x7f080085;
        public static final int sync_pref_group=0x7f080070;
        public static final int sync_pref_group_actions=0x7f080071;
        public static final int sync_pref_group_options=0x7f080072;
        public static final int sync_quiet_desc=0x7f08007e;
        public static final int sync_quiet_title=0x7f08007d;
        public static final int sync_rtm_desc=0x7f080075;
        public static final int sync_rtm_notes=0x7f080084;
        public static final int sync_rtm_title=0x7f080074;
        public static final int tagList_context_create=0x7f080069;
        public static final int tagList_context_delete=0x7f08006b;
        public static final int tagList_context_edit=0x7f08006a;
        public static final int tagList_context_hideTag=0x7f08006d;
        public static final int tagList_context_showTag=0x7f08006c;
        public static final int tagList_menu_sortAlpha=0x7f08006e;
        public static final int tagList_menu_sortSize=0x7f08006f;
        public static final int tagList_titlePrefix=0x7f080068;
        public static final int tags_label=0x7f080039;
        public static final int taskEdit_label=0x7f080032;
        public static final int taskEdit_menu_save=0x7f080057;
        public static final int taskEdit_titleGeneric=0x7f080030;
        public static final int taskEdit_titlePrefix=0x7f080031;
        public static final int taskList_alarmSuffix=0x7f080017;
        public static final int taskList_completedPrefix=0x7f080012;
        public static final int taskList_context_delete=0x7f080023;
        public static final int taskList_context_edit=0x7f080022;
        public static final int taskList_context_postpone=0x7f080026;
        public static final int taskList_context_startTimer=0x7f080024;
        public static final int taskList_context_stopTimer=0x7f080025;
        public static final int taskList_dueIn=0x7f08000f;
        public static final int taskList_elapsedTimePrefix=0x7f080014;
        public static final int taskList_estimatedTimePrefix=0x7f080013;
        public static final int taskList_filter_done=0x7f080029;
        public static final int taskList_filter_hidden=0x7f080028;
        public static final int taskList_filter_tagged=0x7f08002a;
        public static final int taskList_filter_title=0x7f080027;
        public static final int taskList_goalPrefix=0x7f080010;
        public static final int taskList_hiddenPrefix=0x7f08000e;
        public static final int taskList_hiddenSuffix=0x7f08000c;
        public static final int taskList_menu_filters=0x7f08001c;
        public static final int taskList_menu_help=0x7f080021;
        public static final int taskList_menu_insert=0x7f08001a;
        public static final int taskList_menu_more=0x7f08001e;
        public static final int taskList_menu_settings=0x7f080020;
        public static final int taskList_menu_sync=0x7f08001f;
        public static final int taskList_menu_syncshortcut=0x7f08001d;
        public static final int taskList_menu_tags=0x7f08001b;
        public static final int taskList_notesPrefix=0x7f080019;
        public static final int taskList_overdueBy=0x7f080011;
        public static final int taskList_periodicReminderPrefix=0x7f080015;
        public static final int taskList_postpone_dialog=0x7f08002f;
        public static final int taskList_repeatPrefix=0x7f080016;
        public static final int taskList_sort_alpha=0x7f08002c;
        public static final int taskList_sort_auto=0x7f08002b;
        public static final int taskList_sort_duedate=0x7f08002d;
        public static final int taskList_sort_reverse=0x7f08002e;
        public static final int taskList_tagsPrefix=0x7f080018;
        public static final int taskList_titlePrefix=0x7f08000a;
        public static final int taskList_titleTagPrefix=0x7f08000b;
        public static final int taskView_creationDate=0x7f080062;
        public static final int taskView_definiteDueDate=0x7f080060;
        public static final int taskView_elapsed=0x7f08005e;
        public static final int taskView_estimated=0x7f08005f;
        public static final int taskView_notes=0x7f080064;
        public static final int taskView_notifyTitle=0x7f080059;
        public static final int taskView_preferredDueDate=0x7f080061;
        public static final int taskView_tags=0x7f080063;
        public static final int taskView_title=0x7f080058;
        public static final int task_edit_tab_1=0x7f080033;
        public static final int task_edit_tab_2=0x7f080034;
        public static final int task_edit_tab_3=0x7f080035;
    }
    public static final class style {
        public static final int Alert=0x7f0a0000;
        public static final int TextAppearance=0x7f0a0001;
        public static final int TextAppearance_EditEvent_Label=0x7f0a0004;
        public static final int TextAppearance_TaskList_Detail=0x7f0a0003;
        public static final int TextAppearance_TaskList_Task=0x7f0a0002;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
        public static final int sync_preferences=0x7f050001;
    }
}
