/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.timsu.astrid;

public final class R {
    public static final class array {
        /**  Astrid says...  (user should answer yes or no)
         */
        public static final int reminder_responses=0x7f050001;
        /**  Make these < 20 chars so the task name is displayed 
         */
        public static final int reminders=0x7f050000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int importance_1=0x7f060009;
        public static final int importance_2=0x7f06000a;
        public static final int importance_3=0x7f06000b;
        public static final int importance_4=0x7f06000c;
        public static final int taskList_completedDate=0x7f060004;
        public static final int taskList_dueDate=0x7f060003;
        public static final int taskList_dueDateOverdue=0x7f060002;
        public static final int taskList_tags=0x7f060005;
        public static final int task_list_done=0x7f060001;
        public static final int task_list_overdue=0x7f060000;
        public static final int view_header_done=0x7f060006;
        public static final int view_table_overdue=0x7f060008;
        public static final int view_table_values=0x7f060007;
    }
    public static final class drawable {
        public static final int btn_check0=0x7f020000;
        public static final int btn_check25=0x7f020001;
        public static final int btn_check50=0x7f020002;
        public static final int btn_check75=0x7f020003;
        public static final int btn_check_0=0x7f020004;
        public static final int btn_check_25=0x7f020005;
        public static final int btn_check_50=0x7f020006;
        public static final int btn_check_75=0x7f020007;
        public static final int btn_check_off=0x7f020008;
        public static final int btn_check_off_disable=0x7f020009;
        public static final int btn_check_off_disable_focused=0x7f02000a;
        public static final int btn_check_off_longpress=0x7f02000b;
        public static final int btn_check_off_pressed=0x7f02000c;
        public static final int btn_check_off_selected=0x7f02000d;
        public static final int btn_check_on=0x7f02000e;
        public static final int btn_check_on_disable=0x7f02000f;
        public static final int btn_check_on_disable_focused=0x7f020010;
        public static final int btn_check_on_longpress=0x7f020011;
        public static final int btn_check_on_pressed=0x7f020012;
        public static final int btn_check_on_selected=0x7f020013;
        public static final int highlight_longpress=0x7f020014;
        public static final int highlight_pressed=0x7f020015;
        public static final int highlight_selected=0x7f020016;
        public static final int ic_dialog_alert_c=0x7f020017;
        public static final int ic_dialog_info_c=0x7f020018;
        public static final int ic_dialog_time=0x7f020019;
        public static final int ic_dialog_time_c=0x7f02001a;
        public static final int icon=0x7f02001b;
        public static final int strikeout=0x7f02001c;
        public static final int timepicker_down_btn=0x7f02001d;
        public static final int timepicker_down_disabled=0x7f02001e;
        public static final int timepicker_down_disabled_focused=0x7f02001f;
        public static final int timepicker_down_normal=0x7f020020;
        public static final int timepicker_down_pressed=0x7f020021;
        public static final int timepicker_down_selected=0x7f020022;
        public static final int timepicker_input=0x7f020023;
        public static final int timepicker_input_disabled=0x7f020024;
        public static final int timepicker_input_normal=0x7f020025;
        public static final int timepicker_input_pressed=0x7f020026;
        public static final int timepicker_input_selected=0x7f020027;
        public static final int timepicker_up_btn=0x7f020028;
        public static final int timepicker_up_disabled=0x7f020029;
        public static final int timepicker_up_disabled_focused=0x7f02002a;
        public static final int timepicker_up_normal=0x7f02002b;
        public static final int timepicker_up_pressed=0x7f02002c;
        public static final int timepicker_up_selected=0x7f02002d;
        public static final int transparent_button=0x7f02002e;
        public static final int transparent_button_transition=0x7f02002f;
    }
    public static final class id {
        public static final int addAlert=0x7f0a002f;
        public static final int addtask=0x7f0a0036;
        public static final int alert_container=0x7f0a002e;
        public static final int alerts_label=0x7f0a002d;
        public static final int btn_tasklist=0x7f0a0041;
        public static final int btn_viewtask=0x7f0a0040;
        public static final int button1=0x7f0a0002;
        public static final int button_layout=0x7f0a0044;
        public static final int cb1=0x7f0a0038;
        public static final int cell_creationDate=0x7f0a004b;
        public static final int cell_definiteDueDate=0x7f0a0049;
        public static final int cell_elapsed=0x7f0a0047;
        public static final int cell_estimated=0x7f0a0048;
        public static final int cell_notes=0x7f0a004c;
        public static final int cell_preferredDueDate=0x7f0a004a;
        public static final int container=0x7f0a0004;
        public static final int date=0x7f0a0000;
        public static final int decrement=0x7f0a0007;
        public static final int definiteDueDate_date=0x7f0a001c;
        public static final int definiteDueDate_label=0x7f0a001a;
        public static final int definiteDueDate_notnull=0x7f0a001b;
        public static final int definiteDueDate_time=0x7f0a001d;
        public static final int delete=0x7f0a0018;
        public static final int discard=0x7f0a0017;
        public static final int edit=0x7f0a004d;
        public static final int elapsedDuration=0x7f0a0027;
        public static final int elapsedDuration_label=0x7f0a0026;
        public static final int estimatedDuration=0x7f0a0013;
        public static final int estimatedDuration_label=0x7f0a0012;
        public static final int event=0x7f0a000d;
        public static final int flag_after=0x7f0a0033;
        public static final int flag_before=0x7f0a0031;
        public static final int flag_during=0x7f0a0032;
        public static final int flags_label=0x7f0a0030;
        public static final int frame=0x7f0a000b;
        public static final int greeting=0x7f0a003e;
        public static final int hiddenUntil_date=0x7f0a0024;
        public static final int hiddenUntil_label=0x7f0a0022;
        public static final int hiddenUntil_notnull=0x7f0a0023;
        public static final int hiddenUntil_time=0x7f0a0025;
        public static final int image1=0x7f0a0039;
        public static final int importance=0x7f0a0011;
        public static final int importance_label=0x7f0a0010;
        public static final int increment=0x7f0a0005;
        public static final int name=0x7f0a000f;
        public static final int name_label=0x7f0a000e;
        public static final int notes=0x7f0a0029;
        public static final int notes_label=0x7f0a0028;
        public static final int notification=0x7f0a002c;
        public static final int notification_label=0x7f0a002b;
        public static final int numberPicker=0x7f0a0008;
        public static final int preferredDueDate_date=0x7f0a0020;
        public static final int preferredDueDate_label=0x7f0a001e;
        public static final int preferredDueDate_notnull=0x7f0a001f;
        public static final int preferredDueDate_time=0x7f0a0021;
        public static final int progress=0x7f0a0046;
        public static final int prop_layout=0x7f0a003b;
        public static final int row_layout=0x7f0a0037;
        public static final int save=0x7f0a0016;
        public static final int scroll_view=0x7f0a0042;
        public static final int tab_basic=0x7f0a000c;
        public static final int tab_dates=0x7f0a0019;
        public static final int tab_notification=0x7f0a002a;
        public static final int taglist=0x7f0a000a;
        public static final int taglist_layout=0x7f0a0009;
        public static final int tags_container=0x7f0a0015;
        public static final int tags_label=0x7f0a0014;
        public static final int tasklist=0x7f0a0035;
        public static final int tasklist_layout=0x7f0a0034;
        public static final int taskname=0x7f0a003f;
        public static final int text1=0x7f0a0003;
        public static final int text_dueDate=0x7f0a003c;
        public static final int text_layout=0x7f0a003a;
        public static final int text_tags=0x7f0a003d;
        public static final int time=0x7f0a0001;
        public static final int timepicker_input=0x7f0a0006;
        public static final int timerButton=0x7f0a0045;
        public static final int view_layout=0x7f0a0043;
    }
    public static final class layout {
        public static final int edit_alert_item=0x7f030000;
        public static final int edit_tag_item=0x7f030001;
        public static final int importance_spinner_dropdown=0x7f030002;
        public static final int n_number_picker_dialog=0x7f030003;
        public static final int number_picker=0x7f030004;
        public static final int number_picker_dialog=0x7f030005;
        public static final int tag_list=0x7f030006;
        public static final int task_edit=0x7f030007;
        public static final int task_list=0x7f030008;
        public static final int task_list_row=0x7f030009;
        public static final int task_notify=0x7f03000a;
        public static final int task_view=0x7f03000b;
    }
    public static final class plurals {
        public static final int NactiveTasks=0x7f080001;
        /**  Time Constants 
         */
        public static final int Ndays=0x7f080003;
        public static final int Nhours=0x7f080004;
        public static final int Nminutes=0x7f080005;
        public static final int Nseconds=0x7f080006;
        public static final int Ntags=0x7f080002;
        /**  Plurals 
         */
        public static final int Ntasks=0x7f080000;
    }
    public static final class string {
        public static final int add_alert=0x7f070036;
        public static final int addtask_label=0x7f07000f;
        public static final int ago_suffix=0x7f07004c;
        public static final int alerts_label=0x7f070035;
        /**  application 
         */
        public static final int app_name=0x7f070000;
        public static final int blank_button_title=0x7f07003c;
        public static final int blockingOn_label=0x7f07002e;
        public static final int days=0x7f070005;
        public static final int definiteDueDate_label=0x7f07002b;
        public static final int delete_label=0x7f07003b;
        public static final int delete_this_tag_title=0x7f07005c;
        public static final int delete_this_task_title=0x7f07005b;
        public static final int delete_title=0x7f07005a;
        public static final int discard_label=0x7f07003a;
        public static final int edit_label=0x7f070043;
        public static final int elapsedDuration_label=0x7f07002a;
        public static final int error_opening=0x7f070060;
        public static final int error_saving=0x7f070061;
        public static final int estimatedDuration_label=0x7f070029;
        public static final int flag_after=0x7f070034;
        public static final int flag_before=0x7f070032;
        public static final int flag_during=0x7f070033;
        public static final int flags_label=0x7f070031;
        public static final int hiddenUntil_label=0x7f07002d;
        /**  dialog boxes 
         */
        public static final int hour_minutes_dialog=0x7f070037;
        public static final int hours=0x7f070006;
        /**  Importance Labels 
         */
        public static final int importance_1=0x7f070001;
        public static final int importance_2=0x7f070002;
        public static final int importance_3=0x7f070003;
        public static final int importance_4=0x7f070004;
        public static final int importance_label=0x7f070025;
        public static final int information_title=0x7f070056;
        public static final int name_hint=0x7f070024;
        /**  labels 
         */
        public static final int name_label=0x7f070023;
        public static final int no_tags=0x7f070011;
        public static final int notes_hint=0x7f070028;
        public static final int notes_label=0x7f070027;
        public static final int notif_definiteDueDate=0x7f07005e;
        public static final int notif_preferredDueDate=0x7f07005f;
        public static final int notification_dialog=0x7f070038;
        public static final int notification_label=0x7f07002f;
        public static final int notification_prefix=0x7f070030;
        public static final int notify_no=0x7f070059;
        public static final int notify_yes=0x7f070058;
        public static final int overdue_suffix=0x7f07004b;
        public static final int p_notif_quietEnd=0x7f070063;
        public static final int p_notif_quietStart=0x7f070062;
        public static final int preferredDueDate_label=0x7f07002c;
        public static final int progress_dialog=0x7f07004d;
        public static final int progress_suffix=0x7f070042;
        public static final int question_title=0x7f070057;
        /**  buttons 
         */
        public static final int save_label=0x7f070039;
        public static final int startTimer_label=0x7f070040;
        public static final int stopTimer_label=0x7f070041;
        public static final int stop_timer_title=0x7f07005d;
        public static final int tagList_context_create=0x7f07004f;
        public static final int tagList_context_delete=0x7f070051;
        public static final int tagList_context_edit=0x7f070050;
        public static final int tagList_context_hideTag=0x7f070053;
        public static final int tagList_context_showTag=0x7f070052;
        public static final int tagList_menu_sortAlpha=0x7f070054;
        public static final int tagList_menu_sortSize=0x7f070055;
        public static final int tagList_titlePrefix=0x7f07004e;
        public static final int tags_label=0x7f070026;
        public static final int tags_prefix=0x7f070010;
        public static final int taskEdit_menu_save=0x7f07003d;
        public static final int taskEdit_titleGeneric=0x7f07001e;
        public static final int taskEdit_titlePrefix=0x7f07001f;
        public static final int taskList_completedPrefix=0x7f07000c;
        public static final int taskList_context_delete=0x7f070017;
        public static final int taskList_context_edit=0x7f070016;
        public static final int taskList_context_startTimer=0x7f070018;
        public static final int taskList_context_stopTimer=0x7f070019;
        public static final int taskList_dueIn=0x7f07000a;
        public static final int taskList_filter_done=0x7f07001c;
        public static final int taskList_filter_hidden=0x7f07001b;
        public static final int taskList_filter_tagged=0x7f07001d;
        public static final int taskList_filter_title=0x7f07001a;
        public static final int taskList_goalPrefix=0x7f07000b;
        public static final int taskList_hiddenPrefix=0x7f07000e;
        public static final int taskList_hiddenSuffix=0x7f070009;
        public static final int taskList_menu_filters=0x7f070015;
        public static final int taskList_menu_insert=0x7f070012;
        public static final int taskList_menu_settings=0x7f070014;
        public static final int taskList_menu_tags=0x7f070013;
        public static final int taskList_overdueBy=0x7f07000d;
        public static final int taskList_titlePrefix=0x7f070007;
        public static final int taskList_titleTagPrefix=0x7f070008;
        public static final int taskView_creationDate=0x7f070048;
        public static final int taskView_definiteDueDate=0x7f070046;
        public static final int taskView_elapsed=0x7f070044;
        public static final int taskView_estimated=0x7f070045;
        public static final int taskView_notes=0x7f07004a;
        public static final int taskView_notifyTitle=0x7f07003f;
        public static final int taskView_preferredDueDate=0x7f070047;
        public static final int taskView_tags=0x7f070049;
        public static final int taskView_title=0x7f07003e;
        public static final int task_edit_tab_1=0x7f070020;
        public static final int task_edit_tab_2=0x7f070021;
        public static final int task_edit_tab_3=0x7f070022;
    }
    public static final class style {
        public static final int Alert=0x7f090000;
        public static final int TextAppearance=0x7f090001;
        public static final int TextAppearance_EditEvent_Label=0x7f090004;
        public static final int TextAppearance_TaskList_Detail=0x7f090003;
        public static final int TextAppearance_TaskList_Task=0x7f090002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
