#!/bin/bash
# combine multiple android resource xml's to one

cat $1 | /usr/bin/sed 's/<\/resources.*//'
shift
if [ "$*" != "" ]; then
    cat $* | /usr/bin/sed 's/<\/resources.*//;s/<?xml.*//;s/<resources.*//'
fi
echo '</resources>'


